---
# - name: Update all packages
#   yum:
#    name: '*'
#    state: latest

- name: Install EPEL repository
  yum:
    name:
      - epel-release
    state: latest

- name: Install common packages
  yum:
    name:
      - curl
      - wget
      - git
      - ansible
      - python3-pip
      - initscripts
      - yum-utils
    state: latest
  with_items: "{{ common_packages }}"

- name: Install pip
  pip:
    name: pip
    executable: pip3
    state: latest
    extra_args: --upgrade

- name: Install openshift package 
  pip:
    name:
      - ansible
      - openshift
    executable: pip3.6
    extra_args: --user

- name: Make sure that firewalld stopped
  service: name=firewalld state=stopped

- name: Add Google DNS to /etc/resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    block: |
      8.8.8.8
      8.8.4.4
    state: present
  
- name: Add domains to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.7.2 master.example.com master
      192.168.7.3 node1.example.com node1
      192.168.7.4 node2.example.com node2
    state: present

- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable SWAP-1
  shell: |
      swapoff -a
    
- name: Disable SWAP-2
  replace:
    path: /etc/fstab
    regexp: '^(.+ swap .*)$'
    replace: '# \1'

- name: Load required kernel modules for Kubernetes
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ kernel_modules }}"

- name: Modify sysctl entries for Kubernetes
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: True
  with_items: "{{ sysctl_entries }}"